spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&verifyServerCertificate=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
    
    