spring:
   h2:
      console:
         settings:
            webAllowOthers: true  # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
         path: /h2  #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
         enabled: true  #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
   datasource:
      platform: h2 #表明使用的数据库平台是h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:D:/h2db/test
      username: sa
      password: 
      schema: classpath:db/schema.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#     data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
   application:
      name: spring-boot-h2
 

      